### PR TITLE
rewrite init.js to es5 syntax

### PR DESCRIPTION
**Pull request by hitman249**
Old set-top box consoles don't understand es6 syntax

### CODE REVIEW

**Comment by andycandy-de** [comment]
Thank you for your input. I think it should be enough to set the `jsVersionOut` to `ECMASCRIPT5`. ([JsGradleCompiler](https://github.com/leobia/JsGradleCompiler))

[build.gradle](https://github.com/andycandy-de/SimpleAndroidBridge/blob/development/SimpleAndoirdBridgeLibJS/build.gradle)
```gradle
plugins {
    id "com.leobia.gradle.jsgradlecompiler" version "0.3.0"
}

jsOptions {
    inputPath = file("./src/main/js/")
    outputPath = file("./build/js/")
    compilationLevel = "WHITESPACE_ONLY"
    jsVersionIn = 'ECMASCRIPT_2020'
    jsVersionOut = 'ECMASCRIPT_2015'                  // Output Javascript version
    combineAllFiles = false
    keepSameName = false
}
```

You'll have to wait a few weeks for my changes. I'm a bit busy at the moment.

**Comment by hitman249** [comment]
This solution is also far from optimal.

1) You will need to manually add a separate polyfill for promises.
2) The size of the js file will be much larger, since automatic compilation contains numerous helpers for its work.

**Comment by andycandy-de** [comment]
I'm willing to find the best solution for your issue. After considering the options, I still think it's best to simply change the `jsVersionOut` to `ECMASCRIPT5`. This is a small change that's easy for me to maintain. Additionally, I've compared the output of your JavaScript code with the generated output, and the sizes are almost identical.

I also had to modify the JS syntax in [Bridge.kt](https://github.com/andycandy-de/SimpleAndroidBridge/commit/e46537e60604fee171fc9a637c606e99c2ad2164#diff-6d5d46be62cadb4ebbce941fef0c1555cbf60a1ddd0867b176b345ceaf2758e6).

In my opinion, it's better not to add promise functionality to this library. It's easy to add manually to support older web views.

I hope you understand my reasoning. We also need to verify that everything still works as expected. You can check out my branch [feature/javascript_es5](https://github.com/andycandy-de/SimpleAndroidBridge/tree/feature/javascript_es5) and test the functionality with the demo [app](https://github.com/andycandy-de/SimpleAndroidBridge/tree/feature/javascript_es5/app).

If you want to add promise functionality, you can do so using the [script.js](https://github.com/andycandy-de/SimpleAndroidBridge/blob/feature/javascript_es5/app/src/main/assets/www/script.js) file or by using `webView.evaluateJavascript`:
```kotlin
webView.settings.javaScriptEnabled = true
webView.evaluateJavascript(promiseJs)

val bridge = Bridge(applicationContext, webView)
```

I'll need a few days to test the functionality in my development environment.

**Comment by andycandy-de** [comment]
After making a small adjustment, I was able to successfully install the sample application on an Android 4.4 virtual device. @hitman249 Could you please test the [feature/javascript_es5_test](https://github.com/andycandy-de/SimpleAndroidBridge/tree/feature/javascript_es5_test) branch on your physical device to ensure everything works as expected?

**Comment by hitman249** [comment]
There is no way to check now, I can check the release version, after the merge, in my project.

**Comment by andycandy-de** [comment]
OK, I released a new version of the lib
```gradle
    implementation 'com.github.andycandy-de:simple-android-bridge:1.0.3'
```
Just let me know if it works on your physical device. Keep in mind that you have to add the `Promise` by yourself. I hope you understand my decision.
Would be great to get some feedback about the lib :-)

I am closing this pull request.

**Comment by hitman249** [comment]
I will report the results here.

Today I checked Android 6.0, everything works.

**Comment by andycandy-de** [comment]
Could you let me know if you've had a chance to test the changes on the other device? I'm curious to hear about your results.

**Comment by hitman249** [comment]
We did not plan to go below version 6.0.
We have devices with a lower version, but our application will not start there.
Therefore, most likely, if there is a need to go lower, it will be 5.1+, but definitely not 4.1, since devices on this version are simply not capable of playing video in the required quality.

**Pull request closed without merging**
